[package]
name = "reaction-diffusion-rust"
version = "0.1.0"
authors = ["bigbass1997 <bigbass1997.website@gmail.com>"]
edition = "2021"

[dependencies]
minifb = "0.20"
oorandom = "11"
gif = "0.11"
chrono = "0.4"
threadpool = "1"